# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(503, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_first = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_first.setFont(font)
        self.lineEdit_first.setObjectName("lineEdit_first")
        self.horizontalLayout.addWidget(self.lineEdit_first)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_second = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lineEdit_second.setFont(font)
        self.lineEdit_second.setObjectName("lineEdit_second")
        self.horizontalLayout_2.addWidget(self.lineEdit_second)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_add = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_add.clicked.connect(self.add)
        self.horizontalLayout_3.addWidget(self.pushButton_add)
        self.pushButton_minus = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_minus.clicked.connect(self.minus)
        self.horizontalLayout_3.addWidget(self.pushButton_minus)
        self.pushButton_multiply = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_multiply.clicked.connect(self.multiply)
        self.horizontalLayout_3.addWidget(self.pushButton_multiply)
        self.pushButton_divide = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_divide.clicked.connect(self.divide)
        self.horizontalLayout_3.addWidget(self.pushButton_divide)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("QLabel{\n"
                                        "color:green\n"
                                        "}")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def add(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        self.label_result.setText("Addition: " + str(fnum + secnum))

    def minus(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        self.label_result.setText("Minus: " + str(fnum - secnum))

    def multiply(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        self.label_result.setText("Multiplication: " + str(fnum * secnum))

    def divide(self):
        fnum = int(self.lineEdit_first.text())
        secnum = int(self.lineEdit_second.text())
        self.label_result.setText("Divide: " + str(fnum / secnum))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.label.setText(_translate("Form", "First Number"))
        self.lineEdit_first.setPlaceholderText(_translate("Form", "Enter first number"))
        self.label_2.setText(_translate("Form", "Second Number"))
        self.lineEdit_second.setPlaceholderText(_translate("Form", "Enter second number"))
        self.pushButton_add.setText(_translate("Form", "+"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_multiply.setText(_translate("Form", "*"))
        self.pushButton_divide.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
