# Form implementation generated from reading ui file 'RadioDemo.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(734, 534)
        Dialog.setStyleSheet("QLabel{\n"
                             "\n"
                             "color:rgb(170, 0, 255)\n"
                             "}")
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setGeometry(QtCore.QRect(9, 357, 716, 168))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("QLabel{\n"
                                        "\n"
                                        "color:rgb(170, 0, 255)\n"
                                        "}")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(9, 9, 175, 134))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_py = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.radioButton_py.setFont(font)
        self.radioButton_py.setObjectName("radioButton_py")
        self.radioButton_py.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.radioButton_py)
        self.radioButton_js = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.radioButton_js.setFont(font)
        self.radioButton_js.setObjectName("radioButton_js")
        self.radioButton_js.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.radioButton_js)
        self.radioButton_java = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.radioButton_java.setFont(font)
        self.radioButton_java.setObjectName("radioButton_java")
        self.verticalLayout.addWidget(self.radioButton_java)
        self.radioButton_java.toggled.connect(self.radio_selected)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(9, 183, 293, 134))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_card = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.radioButton_card.setFont(font)
        self.radioButton_card.setObjectName("radioButton_card")
        self.radioButton_card.toggled.connect(self.radio_selected)
        self.verticalLayout_2.addWidget(self.radioButton_card)
        self.radioButton_paypal = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.radioButton_paypal.setFont(font)
        self.radioButton_paypal.setObjectName("radioButton_paypal")
        self.radioButton_paypal.toggled.connect(self.radio_selected)
        self.verticalLayout_2.addWidget(self.radioButton_paypal)
        self.radioButton_alipay = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.radioButton_alipay.setFont(font)
        self.radioButton_alipay.setObjectName("radioButton_alipay")
        self.radioButton_alipay.toggled.connect(self.radio_selected)
        self.verticalLayout_2.addWidget(self.radioButton_alipay)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        selected1 = ""
        selected2 = ""
        if self.radioButton_py.isChecked() == True:
            selected1 = "Python"
        if self.radioButton_java.isChecked() == True:
            selected1 = "Java"
        if self.radioButton_js.isChecked() == True:
            selected1 = "JavaScript"

        if self.radioButton_card.isChecked() == True:
            selected2 = "Debit/Credit Card"
        if self.radioButton_paypal.isChecked() == True:
            selected2 = "Paypal"
        if self.radioButton_alipay.isChecked() == True:
            selected2 = "Alipay"

        self.label_result.setText("Chosen Book: " + selected1 + "\nChosen Payment Method: " + selected2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose Your Book"))
        self.radioButton_py.setText(_translate("Dialog", "Python"))
        self.radioButton_js.setText(_translate("Dialog", "JavaScript"))
        self.radioButton_java.setText(_translate("Dialog", "Java"))
        self.label_2.setText(_translate("Dialog", "Choose Your Payment Method"))
        self.radioButton_card.setText(_translate("Dialog", "Debit/Credit Card"))
        self.radioButton_paypal.setText(_translate("Dialog", "Paypal"))
        self.radioButton_alipay.setText(_translate("Dialog", "Alipay"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
